runtime: nodejs20

handlers:
  # Serve all static files from the 'dist' folder
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
